### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by 8188** [defog-ai/sqlcoder#44]
I use 7b-model with 3090(**24G**), When loading, it cost 15G Memory, It's OK. 
When referencing, indeed it is a nice model, but it eat too much Memory as metadata.sql increasing a bit. 
Only a **4k metadata.sql** probably causes CUDA out of memory. Any good idea to solve it?

**Comment by deqncho2** [comment]
I'm interested in the same question. How do we feed in large schemas (I'm talking > 10k) without running out of memory on inference?

**Comment by fire717** [comment]
Same question here.

**Comment by dqatsh** [comment]
try

load_in_4bit=True
&
num_beams=3

it works for me with 4090(24G)
